Django/example/02-basic/main/editors/urls.py
from django.urls import path

from . import views

app_name = 'editors'
urlpatterns = [
    path('create/', views.EditorCreate.as_view(), name = 'create'),
    path('', views.EditorsList.as_view(), name = 'list'), # Read
    path('<int:pk>/update/', views.EditorUpdate.as_view(), name = 'update'),
    path('<int:pk>/delete/', views.EditorDelete.as_view(), name = 'delete'),
]

Django/example/02-basic/main/main/urls.py
from django.contrib import admin
from django.urls import path, include # <- `include` を追加

urlpatterns = [
    path('admin/', admin.site.urls),

    # note
    # 第1引数には ``<`~python.exe manage.py startapp xxx` で作成したアプリ名>/`` を指定
    # 第2引数には ``include('<`~python.exe manage.py startapp xxx` で作成したアプリ名>.urls')`` を指定
    path('editors/', include('editors.urls')),
]

Django/example/02-basic/main/editors/models.py
from django.db import models

# Create your models here.

# note
# ここに定義するクラス名が、DB 内のテーブル定義に該当する。
class Editor(models.Model):

    # note
    # ここに定義するクラス変数名が、DB 内のカラム定義に該当する。
    id = models.AutoField(verbose_name = 'ID', primary_key = True)
    name = models.CharField(verbose_name = '名前', max_length = 255)

Django/example/02-basic/main/editors/forms.py
from django import forms

from .models import Editor

class EditorEditForm(forms.ModelForm):
    class Meta:
        model = Editor
        fields = (
            'name',
        )

Django/example/02-basic/main/editors/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView

from .models import Editor
from .forms import EditorEditForm

# Create your views here.

class EditorCreate(CreateView):
    model = Editor
    form_class = EditorEditForm
    template_name = 'editors/form.html'
    success_url = reverse_lazy('editors:list')

class EditorsList(ListView):
    model = Editor
    template_name = 'editors/list.html'
    success_url = reverse_lazy('editors:list')

class EditorUpdate(UpdateView):
    model = Editor
    form_class = EditorEditForm
    template_name = 'editors/form.html'
    success_url = reverse_lazy('editors:list')

class EditorDelete(DeleteView):
    model = Editor
    success_url = reverse_lazy('editors:list')

Django/example/02-basic/main/templates/base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
{% block extra_css %}{% endblock %}
<title>{% block title %}My books{% endblock %}</title>
</head>
<body>
  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/utility.js' %}"></script>
{% block scripts %}
  {{ scripts }}
{% endblock %}
</body>
</html>

Django/example/02-basic/main/templates/editors/form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load widget_tweaks %}

{% block title %}編集者の{% if object %}編集{% else %}追加{% endif %}{% endblock title %}

{% block content %}
    <h4 class="mt-4 mb-5 border-bottom">編集者の{% if object %}編集{% else %}追加{% endif %}</h4>
    <form method="post">
      {% csrf_token %}{# Cross Site Request Forgery protection https://docs.djangoproject.com/en/4.0/ref/csrf/ #}
      
      <div class="mb-3">
        {{ form.name.label_tag}}
        {{ form.name | add_class:"form-control"}}{# `form-control` の意味は右参照 https://getbootstrap.jp/docs/5.0/forms/form-control/ #}
      </div>
      
      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <button type="submit" class="btn btn-primary">登録</button>
        </div>
      </div>
    </form>
    <a href="{% url 'editors:list' %}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}

Django/example/02-basic/main/templates/editors/list.html
{% extends "base.html" %}

{% block title %}編集者の一覧{% endblock title %}

{% block content %}
    <h4 class="mt-4 border-bottom">編集者の一覧</h4>
    <a href="{% url 'editors:create' %}" class="btn btn-primary btn-sm my-3">追加</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">名前</th>
          <th scope="col">操作</th>
        </tr>
      </thead>
      <tbody>
        {# views.py の `class EditorsList(ListView):` で、 #}
        {# `model = Editor` することで `object_list` に、 #}
        {# models.py の `class Editor(models.Model):` 達が入る #}
        {% for editor in object_list %}
        <tr>
          <th scope="row">{{ editor.id }}</th>
          <td>{{ editor.name }}</td>
          <td>
            <a href="{% url 'editors:update' editor.id %}" class="btn btn-outline-primary btn-sm">編集</a>
            
            <!-- フィールド `id` を javascript で使用したいため、`data-??` を使用して渡す -->
            <!-- https://developer.mozilla.org/ja/docs/Web/API/HTMLElement/dataset -->
            <a href="javascript:void(0)" data-id="{{ editor.id }}" class="btn btn-outline-primary btn-sm deletion-submitted">削除</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock content %}
{% block scripts %}
<script>
  $(document).ready(()=>{

    // レコードの削除
    $('.deletion-submitted').on('click', function(){ // 削除ボタンクリック時

      // 削除用 URL を POST で叩く
      $.ajax({
        url: '/editors/' + this.dataset.id + '/delete/',
        method: 'POST',
        
        // Setting the token on the AJAX request
        // https://docs.djangoproject.com/en/4.0/ref/csrf/#setting-the-token-on-the-ajax-request
        headers: {'X-CSRFToken': dict_utilities.getValueFromCookie('csrftoken')},
      }).done(() =>{
        location.reload();
      });
    });
  });
</script>
{% endblock scripts %}