Django/example/14-PostgreSQL/main/accounts/urls.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.generic import CreateView

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', CreateView.as_view(
        template_name = 'accounts/form.html',
        form_class = UserCreationForm,
        success_url = '/',
    ), name='signup'),
    path('login/', LoginView.as_view(
        redirect_authenticated_user = True,
        # note
        # ログインページにアクセスする認証済みユーザーが、ログインに成功したかのようにリダイレクトさせる。
        # https://docs.djangoproject.com/en/4.0/topics/auth/default/#django.contrib.auth.views.LoginView.redirect_authenticated_user
        
        template_name = 'accounts/login.html'
    ), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', views.AccountCreateView.as_view(), name='create'),
    path('', views.AccountsListView.as_view(), name = 'list'), # Read
    path('<int:pk>/delete/', views.AccountDelete.as_view(), name = 'delete'),
    path('<int:pk>/token/create/', views.createToken, name = 'create_token'),
    path('<int:pk>/token/delete/', views.deleteToken, name = 'delete_token'),
]

Django/example/14-PostgreSQL/main/authors/urls.py
from django.urls import path

from . import views

app_name = 'authors'
urlpatterns = [
    path('create/', views.AuthorCreate.as_view(), name = 'create'),
    path('', views.AuthorsList.as_view(), name = 'list'), # Read
    path('<int:pk>/update/', views.AuthorUpdate.as_view(), name = 'update'),
    path('<int:pk>/delete/', views.AuthorDelete.as_view(), name = 'delete'),
    path('export_as_csv/', views.export_as_csv, name = 'export_as_csv'),
    path('import_from_csv/', views.import_from_csv, name = 'import_from_csv'),
]

Django/example/14-PostgreSQL/main/editors/urls.py
from django.urls import path

from . import views

app_name = 'editors'
urlpatterns = [
    path('create/', views.EditorCreate.as_view(), name = 'create'),
    path('', views.EditorsList.as_view(), name = 'list'), # Read
    path('<int:pk>/update/', views.EditorUpdate.as_view(), name = 'update'),
    path('<int:pk>/delete/', views.EditorDelete.as_view(), name = 'delete'),
    path('export_as_csv/', views.export_as_csv, name = 'export_as_csv'),
    path('import_from_csv/', views.import_from_csv, name = 'import_from_csv'),
]

Django/example/14-PostgreSQL/main/main/urls.py
from django.contrib import admin
from django.urls import path, include # <- `include` を追加

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('admin/', admin.site.urls),

    # note
    # 第1引数には ``<`~python.exe manage.py startapp xxx` で作成したアプリ名>/`` を指定
    # 第2引数には ``include('<`~python.exe manage.py startapp xxx` で作成したアプリ名>.urls')`` を指定
    path('editors/', include('editors.urls')),
    path('accounts/', include('accounts.urls')),
    path('authors/', include('authors.urls')),
    path('', include('index.urls')),
    # URL で API のメジャーバージョンが指定できるように、`v1/` を URL に追加
    path('api/v1/', include('common.apiv1_urls')),
    
    # Open API 準拠の API ドキュメント生成の為の定義
    # https://drf-spectacular.readthedocs.io/en/latest/readme.html#take-it-for-a-spin
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

Django/example/14-PostgreSQL/main/templates/base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
{% block extra_css %}{% endblock %}
<title>{% block title %}My books{% endblock %}</title>
</head>
<body>
  <nav class="navbar navbar-expand flex-md-row navbar-dark bg-dark">
    <div class="container justify-content-between">
      <a href="/" class="navbar-brand">書籍ライブラリ</a>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {# ドロップダウンの実装方法は右参照 https://getbootstrap.jp/docs/5.0/components/navbar/#nav #}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuBooks" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            書籍
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuBooks">
            <li><a class="dropdown-item" href="/">書籍の一覧</a></li>
            <li><a class="dropdown-item" href="{% url 'authors:list' %}">著者の一覧</a></li>
            <li><a class="dropdown-item" href="{% url 'editors:list' %}">編集者の一覧</a></li>
          </ul>
        </li>
      </ul>
      <ul class="navbar-nav mr-md-2">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuAccounts" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {# ユーザーがログインしているかどうかは、`user.is_authenticated` で判定できる #}
            {# https://docs.djangoproject.com/en/4.0/ref/contrib/auth/#django.contrib.auth.models.User.is_authenticated #}
            {% if user.is_authenticated %}
            {# ユーザー名は、`user.username` で取得できる #}
            {# https://docs.djangoproject.com/en/4.0/ref/contrib/auth/#django.contrib.auth.models.User.username #}
            {{ user.username }}
            {% else %}
            ログアウト中
            {% endif %}
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuAccounts">
            <li>
              <a class="dropdown-item" href="{% url 'accounts:list' %}">ユーザーの一覧</a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'swagger-ui' %}">API ドキュメント (Swagger UI)</a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'redoc' %}">API ドキュメント (ReDoc)</a>
            </li>
            {% if user.is_authenticated %}
            <li>
              <button type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#logoutModal">ログアウト</button>
            </li>
            {% endif %}
          </ul>
        </li>
        {% if not user.is_authenticated %}
        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">ユーザー登録</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <!-- ログアウトを確認するモーダルダイアログ -->
  <div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">ログアウト確認</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>ログアウトしますか？</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
          <a class="btn btn-primary" href="{% url 'accounts:logout' %}" role="button">ログアウト</a> {# `<a>` タグをボタンの見た目にする方法は右参照 https://getbootstrap.jp/docs/5.0/components/buttons/#button-tags #}
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/utility.js' %}"></script>
{% block scripts %}
  {{ scripts }}
{% endblock %}
</body>
</html>

Django/example/14-PostgreSQL/main/templates/form.html
{% load widget_tweaks %}
<div class="mb-3">
    
    {{ obj_field.label_tag}}{% if obj_field.field.required %} ※{% endif %}{# フィールドが入力必須フィールドなら「※」を表示 #}
    {% if str_help_message %}<i title="{{str_help_message}}"> ？</i>{% endif %}{# `str_help_message` を定義している場合は「？」を表示してマウスオーバー時にポップアップで表示 #}
    
    {% if obj_field.errors %}{# `errors` の意味は右参照 https://docs.djangoproject.com/en/4.0/ref/forms/api/ #}
        
    {% if obj_field.widget_type == 'select' %}{# `widget_type` の意味は右参照 https://docs.djangoproject.com/ja/4.0/ref/forms/api/#django.forms.BoundField.widget_type #}
    {# django-widget-tweaks の `add_class` を利用してクラスを追加 #}
    {# https://pypi.org/project/django-widget-tweaks/ #}
    {{ obj_field | add_class:"form-select is-invalid"}}
    {# `form-select` の意味は右参照 https://getbootstrap.jp/docs/5.0/forms/select/ #}
    {# `is-invalid` の意味は右参照 https://getbootstrap.jp/docs/5.0/forms/validation/ #}
    {% elif obj_field.widget_type == 'date' %}
    {{ obj_field | attr:"type:date" | add_class:"form-control is-invalid"}}
    {% else %}
    {{ obj_field | add_class:"form-control is-invalid"}}
    {# `form-control` の意味は右参照 https://getbootstrap.jp/docs/5.0/forms/form-control/ #}
    {% endif %}
    
    {% for errorObj in obj_field.errors %}
    <div class="invalid-feedback">{# `invalid-feedback` の意味は右参照 https://getbootstrap.jp/docs/5.0/forms/validation/ #}
        {{ errorObj | escape }}{# `escape` の意味は右参照 https://docs.djangoproject.com/en/4.0/ref/templates/builtins/#escape #}
    </div>
    {% endfor %}

    {% else %}
    {% if obj_field.widget_type == 'select' %}
    {{ obj_field | add_class:"form-select"}}
    {% elif obj_field.widget_type == 'date' %}
    {{ obj_field | attr:"type:date" | add_class:"form-control"}}
    {% else %}
    {{ obj_field | add_class:"form-control"}}
    {% endif %}
    {% endif %}

</div>

Django/example/14-PostgreSQL/main/templates/form_dual.html
{% load widget_tweaks %}

<script>
document.addEventListener("DOMContentLoaded", function() {
    $("#{{ obj_field.id_for_label }}").bootstrapDualListbox({
        filterTextClear:'全件表示',
        filterPlaceHolder:'検索',
        moveSelectedLabel:'選択済みに移動します。',
        moveAllLabel:'全てを選択済みに移動します。',
        removeSelectedLabel:'未選択に移動します。',
        removeAllLabel:'全てを未選択に移動します。',
        moveOnSelect: false,
        nonSelectedListLabel: "未選択",
        selectedListLabel: "選択済み",
        infoText:'{0}件',
        showFilterInputs:true,
        infoTextEmpty:'0件',
        infoTextFiltered:'{1}件中{0}件表示',
    });
})
</script>

<div class="mb-3">
    {{ obj_field.label_tag}}{% if obj_field.field.required %} ※{% endif %}
    {% if str_help_message %}<i title="{{str_help_message}}"> ？</i>{% endif %}

    <div>
        {% if obj_field.errors %}
        <select name="{{ obj_field.name }}" class="form-select is-invalid" id="{{ obj_field.id_for_label }}" multiple>
        {% for node in obj_field %}
            <option value="{{ node.data.value }}" id="{{ obj_field.id_for_label }}_{{ node.data.attrs.id }}"{% if node.data.selected %} selected{% endif %}>{{ node.data.label }}</option>
        {% endfor %}
        </select>
        {% for error in obj_field.errors %}
        <div class="invalid-feedback">
            {{ error | escape }}
        </div>
        {% endfor %}
        {% else %}
        <select name="{{ obj_field.name }}" class="form-select" id="{{ obj_field.id_for_label }}" multiple>
        {% for node in obj_field %}
            <option value="{{ node.data.value }}" id="{{ obj_field.id_for_label }}_{{ node.data.attrs.id }}"{% if node.data.selected %} selected{% endif %}>{{ node.data.label }}</option>
        {% endfor %}
        </select>
        {% endif %}
    </div>
</div>