Django/example/15-json-field/main/authors/urls.py
from django.urls import path

from . import views

app_name = 'authors'
urlpatterns = [
    path('create/', views.AuthorCreate.as_view(), name = 'create'),
    path('', views.AuthorsList.as_view(), name = 'list'), # Read
    path('<int:pk>/update/', views.AuthorUpdate.as_view(), name = 'update'),
    path('<int:pk>/delete/', views.AuthorDelete.as_view(), name = 'delete'),
    path('export_as_csv/', views.export_as_csv, name = 'export_as_csv'),
    path('import_from_csv/', views.import_from_csv, name = 'import_from_csv'),
]

Django/example/15-json-field/main/main/urls.py
from django.contrib import admin
from django.urls import path, include # <- `include` を追加

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('admin/', admin.site.urls),

    # note
    # 第1引数には ``<`~python.exe manage.py startapp xxx` で作成したアプリ名>/`` を指定
    # 第2引数には ``include('<`~python.exe manage.py startapp xxx` で作成したアプリ名>.urls')`` を指定
    path('editors/', include('editors.urls')),
    path('accounts/', include('accounts.urls')),
    path('authors/', include('authors.urls')),
    path('', include('index.urls')),
    # URL で API のメジャーバージョンが指定できるように、`v1/` を URL に追加
    path('api/v1/', include('common.apiv1_urls')),
    
    # Open API 準拠の API ドキュメント生成の為の定義
    # https://drf-spectacular.readthedocs.io/en/latest/readme.html#take-it-for-a-spin
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

Django/example/15-json-field/main/authors/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
    id = models.AutoField(verbose_name = 'ID', primary_key = True)
    name = models.CharField(verbose_name = '名前', max_length = 255, unique = True)
    birthday = models.DateField(verbose_name = '生年月日', null = True, blank = True)

    def __str__(self):
        return self.name

Django/example/15-json-field/main/authors/forms.py
from unicodedata import name
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator

from .models import Author

class AuthorEditForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = (
            'name',
            'birthday',
        )

class AuthorCSVForm(forms.Form):
    
    id = forms.IntegerField(
        validators = [
            MinValueValidator(limit_value = -2147483648, message = 'ID は -2147483648 から 2147483647 の範囲を指定してください。'),
            MaxValueValidator(limit_value = 2147483647, message = 'ID は -2147483648 から 2147483647 の範囲を指定してください。'),
        ]
    )
    name = forms.CharField(max_length = 255)
    birthday = forms.DateField(required = False)

Django/example/15-json-field/main/authors/views.py
import csv
import io
import logging
import time

from django.db import transaction
from django.db.utils import OperationalError, IntegrityError
from django.forms.models import model_to_dict
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.decorators.http import require_safe, require_POST
from django.views.generic import CreateView, ListView, UpdateView, DeleteView

from common.const import FL_SLEEP_TIME_OF_RETRYING_CAUSE_OF_DEADLOCK, INT_TIMES_OF_RETRYING_CAUSE_OF_DEADLOCK
from common.forms import CSVImputForm
from common.utilities import makeCSVStringFromDict, makeVerboseNameVsFieldNameDict, getOrdinalString, getQeryStringInURL
from common.views import TokenAPIViewForCreation, TokenAPIViewForList, TokenAPIViewForUpdate, TokenAPIViewForDeletion

from .models import Author
from .forms import AuthorEditForm, AuthorCSVForm
from .serializer import AuthorSerializerForQueryString, AuthorSerializerForCreate, AuthorSerializerForUpdate

# Create your views here.

logger = logging.getLogger(__name__)

class AuthorCreate(CreateView):
    model = Author
    form_class = AuthorEditForm
    template_name = 'authors/form.html'
    success_url = reverse_lazy('authors:list')

class AuthorsList(ListView):
    model = Author
    template_name = 'authors/list.html'
    success_url = reverse_lazy('authors:list')

class AuthorUpdate(UpdateView):
    model = Author
    form_class = AuthorEditForm
    template_name = 'authors/form.html'
    success_url = reverse_lazy('authors:list')

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors:list')

def makeDictFromAuthors(cls, model_authors):
    """
    著者リストを辞書配列化する
    """
    dict_authors = []
    for model_edtir in model_authors:
        dict_tmp = model_to_dict(model_edtir)
        dict_authors.append(dict_tmp)
    return dict_authors

@require_safe
def export_as_csv(request):
    
    # 
    # 以下の形式のディクショナリを生成
    # ```
    # {
    #     'ID' : 'id',
    #     '名前' : 'name',
    #     '生年月日' : 'birthday',
    # }
    # ```
    dict_verboseNameVsFieldName = makeVerboseNameVsFieldNameDict(Author())

    obj_idSortedAuthors = Author.objects.all().order_by('id')
    dict_authors = makeDictFromAuthors(None, obj_idSortedAuthors) # 編集者リストを辞書配列化
    str_csv = makeCSVStringFromDict(dict_authors, dict_verboseNameVsFieldName.keys()) # 辞書配列を CSV 文字列化

    # CSV ファイルにして出力
    obj_response = HttpResponse(str_csv, content_type = 'text/csv; charsert=utf-8-sig')
    obj_response['Content-Disposition'] = 'attachment; filename="authors.csv"'

    return obj_response

@require_POST
def import_from_csv(request):
    
    obj_csvImportForm = CSVImputForm(request.POST, request.FILES)

    #
    # インスタンス化したフォームクラスの `.is_valid()` をコールすることで、  
    # バリデーションを確認することができる。  
    # ここでは、CSVImputForm のバリデーションエラーとなっていないかどうかを確認している。
    # 以下のようなパターンの場合に、バリデーションエラーとなる。  
    # e.g.
    #  - `mode` フィールドが存在しない
    #  - `mode` フィールドの値が `update` でも `replace` でもない
    #  - ファイルが指定されていない
    if not obj_csvImportForm.is_valid():
        for str_key, str_errmsgs in obj_csvImportForm.errors.items():
            logger.warning(f'{str_key}: "{str_errmsgs[0]}"')
        return redirect('authors:list') # 一覧へ遷移

    obj_toImportAuthors = []
    str_fileName = request.FILES['file'].name
    with io.TextIOWrapper(request.FILES['file'], encoding = 'utf-8-sig') as stream:

        obj_reader = csv.DictReader(stream)

        try:
            str_verboseNamesInProbe = obj_reader.fieldnames
        except UnicodeDecodeError as err:
            # e.g. ファイルの文字コードが SJIS で保存されていた場合
            logger.warning(f'`UnicodeDecodeError` has occured while opening "{str_fileName}". Reason: "{err.reason}"')
            return redirect('authors:list') # 一覧へ遷移

        dict_verboseNameVsFieldName = makeVerboseNameVsFieldNameDict(Author())
        str_requiredHeaders = dict_verboseNameVsFieldName.keys()

        # 必要なカラムタイトルが存在するかどうかチェック
        for str_requiredHeader in str_requiredHeaders:
            if str_requiredHeader not in str_verboseNamesInProbe:
                logger.warning(f'Required header `{str_requiredHeader}` is not defined in "{str_fileName}"')
                return redirect('authors:list') # 一覧へ遷移

        for dict_readRow in obj_reader:
            
            # 必要なプロパティ定義だけをもったディクショナリを生成
            dict_subject = {dict_verboseNameVsFieldName[str_verboseName]: dict_readRow[str_verboseName] for str_verboseName in dict_verboseNameVsFieldName.keys()}

            obj_subjectAuthor = AuthorCSVForm(dict_subject)

            if obj_subjectAuthor.is_valid(): # バリデーション OK の場合
                obj_toImportAuthors.append(obj_subjectAuthor.cleaned_data)  

            else: # バリデーションエラーの場合
                str_tmp = ', '.join([f'{str_key}: "{var_val}"' for str_key, var_val in dict_readRow.items()])
                logger.warning(f'Validation error has occured while loading {str_tmp}. Check following.')
                for str_key, str_errmsgs in obj_subjectAuthor.errors.items():
                    logger.warning(f'{str_key}: "{str_errmsgs[0]}"')

    #
    # トランザクション試行ループ。  
    # 複数ユーザーから同時にこの機能が実行されると、DB のデッドロックが発生する可能性があるため、  
    # SQL 文が発行されるコードは以下の `with transaction.atomic():` 内で記述し、  
    # デッドロックが発生した場合は `OperationalError` が発生するのでそれをキャッチ。  
    # 一定時間スリープしてリトライする。  
    bl_retrying = True
    int_tryTime = 1
    while bl_retrying:
        try:
            with transaction.atomic():
                # この with 文内で実行される SQL 文はまとめて実行される。

                # 全ての ID リストをここで取得し、レコードを更新する度にこのリストから ID を削除していく。
                dict_notUpdatedIDs = {obj_editors.id: obj_editors.id for obj_editors in Author.objects.all()}

                for obj_toImportAuthor in obj_toImportAuthors:

                    try:
                        Author.objects.update_or_create(
                            id = obj_toImportAuthor['id'],
                            defaults = {
                                'name': obj_toImportAuthor['name'],
                                'birthday': obj_toImportAuthor['birthday'],
                            }
                        )
                        
                        # レコードを更新したのでリストから ID を削除
                        dict_notUpdatedIDs.pop(obj_toImportAuthor['id'], None)

                    except IntegrityError as err: # `名前` フィールドが他レコードと重複した場合
                        str_tmp = ', '.join([f'{str_key}: "{var_val}"' for str_key, var_val in obj_toImportAuthor.items()])
                        logger.warning(f'`IntegrityError` has occured while saving {str_tmp}. Check following.')
                        logger.warning(err)
                
                # `置き換え` モードの場合
                if obj_csvImportForm.cleaned_data.get('mode') == 'replace':
                    for int_notUpdatedID in dict_notUpdatedIDs.values():
                        Author.objects.filter(id = int_notUpdatedID).first().delete()


        except OperationalError as err:
            # デッドロックの可能性。既定回数分リトライする。
            
            logger.warning(f'There is a possibility of deadlock. This is the {getOrdinalString(int_tryTime)} time attempt. Check following.')
            logger.warning(str(err))

            if int_tryTime < INT_TIMES_OF_RETRYING_CAUSE_OF_DEADLOCK: # 既定回数以内の場合
                # スリープして再試行
                time.sleep(FL_SLEEP_TIME_OF_RETRYING_CAUSE_OF_DEADLOCK)
                int_tryTime += 1
                logger.warning('Transaction retrying...')
                continue

            else:
                logger.error(f'The number of record saving attempts has reached the upper limit ({INT_TIMES_OF_RETRYING_CAUSE_OF_DEADLOCK} times).')
        
        # `OperationalError` が発生しなかった場合または `OperationalError` が規定回数繰り返し発生した場合
        bl_retrying = False
    
    return redirect('authors:list')

class AuthorCreateAPIView(TokenAPIViewForCreation):
    property_keyword = 'authors'
    serializer = AuthorSerializerForCreate

class AuthorListAPIView(TokenAPIViewForList):
    model = Author
    property_keyword = 'authors'
    serializer = AuthorSerializerForQueryString
    dictionarizer = makeDictFromAuthors

class AuthorUpdateAPIView(TokenAPIViewForUpdate):
    model = Author
    property_keyword = 'authors'
    serializer = AuthorSerializerForUpdate

class AuthorDeleteAPIView(TokenAPIViewForDeletion):
    model = Author


from rest_framework import status, serializers

from drf_spectacular.extensions import OpenApiViewExtension
from drf_spectacular.utils import extend_schema, extend_schema_serializer, OpenApiParameter, OpenApiResponse, OpenApiExample
# https://drf-spectacular.readthedocs.io/en/latest/drf_spectacular.html?highlight=openapiviewextension#drf_spectacular.extensions.OpenApiViewExtension
# https://drf-spectacular.readthedocs.io/en/latest/blueprints.html?highlight=Fixed#dj-stripe

from common.views import InvalidReasonSerializerForDoc

class AuthorCreationSerializerForDoc(serializers.Serializer):
    name = serializers.CharField(help_text = '名前を指定します。他の著者と同じの名前は登録できません。また、空文字も無効です。')
    birthday = serializers.CharField(help_text = '任意で生年月日を指定します。', required = False)

class AuthorCreationArraySerializerForDoc(serializers.Serializer):
    class AuthorCreationSerializer(AuthorCreationSerializerForDoc):
        pass
    editors = AuthorCreationSerializer(many = True)

class AuthorCreateOpenApiView(OpenApiViewExtension):

    target_class = AuthorCreateAPIView

    def view_replacement(self):
        
        class Fixed(self.target_class):

            null = None
            
            @extend_schema(
                tags = ['著者管理'],
                operation_id = '著者の追加',
                description = '著者を追加します。',
                request = AuthorCreationArraySerializerForDoc,
                responses = {
                    status.HTTP_200_OK: None,
                    status.HTTP_400_BAD_REQUEST: OpenApiResponse(
                        response = InvalidReasonSerializerForDoc,

Django/example/15-json-field/main/templates/authors/form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}著者の{% if object %}編集{% else %}追加{% endif %}{% endblock title %}

{% block content %}
    <h4 class="mt-4 mb-5 border-bottom">著者の{% if object %}編集{% else %}追加{% endif %}</h4>
    <form method="post">
      {% csrf_token %}
      
      {% include "form.html" with obj_field=form.name str_help_message="著者の名前を入力します。"%}
      {% include "form.html" with obj_field=form.birthday str_help_message="任意で著者の生年月日を入力します。"%}
      
      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <button type="submit" class="btn btn-primary">登録</button>
        </div>
      </div>
    </form>
    <a href="{% url 'authors:list' %}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}

Django/example/15-json-field/main/templates/authors/list.html
{% extends "base.html" %}

{% block title %}著者の一覧{% endblock title %}

{% block content %}
    <h4 class="mt-4 border-bottom">著者の一覧</h4>
    <a href="{% url 'authors:create' %}" class="btn btn-primary btn-sm my-3">追加</a>
    <a href="{% url 'authors:export_as_csv' %}" class="btn btn-primary btn-sm my-3">CSV 出力</a>
    <button class="btn btn-primary btn-sm my-3" id="csv-input-btn">CSV 入力</button>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">名前</th>
          <th scope="col">生年月日</th>
          <th scope="col">操作</th>
        </tr>
      </thead>
      <tbody>
        {% for author in object_list %}
        <tr>
          <th scope="row">{{ author.id }}</th>
          <td>{{ author.name }}</td>
          <td>{% if author.birthday %}{{ author.birthday }}{% else %} - {% endif %}</td>
          <td>
            <a href="{% url 'authors:update' author.id %}" class="btn btn-outline-primary btn-sm">編集</a>
            <a href="javascript:void(0)" data-id="{{ author.id }}" data-delete_confirmation_message="著者 {{ author.name }} を削除しますか？" class="btn btn-outline-primary btn-sm delete-btn">削除</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    
    <!-- 削除を確認するモーダルダイアログ -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">削除確認</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p id="delete-confirmation-message"></p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
            <button type="button" class="btn btn-primary" id="deletion-submitted">削除</button>
          </div>
        </div>
      </div>
    </div>
    <!-- CSV 入力のモーダルダイアログ -->
    <div class="modal fade" id="CSVInputModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">CSV 入力</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <form action="{% url "authors:import_from_csv" %}" enctype="multipart/form-data" method="post">
            <div class="modal-body">
              {% csrf_token %}
              <div class="mb-2">
                <input type="file" name="file" class="form-control" id="csv-input">
              </div>
              <div class="mb-2">
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="mode" id="inlineRadio1" value="update" checked>
                  <label class="form-check-label" for="inlineRadio1">更新及び追加</label>
                </div>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="mode" id="inlineRadio2" value="replace">
                  <label class="form-check-label" for="inlineRadio2">置き換え</label>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
              <input type="submit" class="btn btn-primary" value="反映"></input>
            </div>
          </form>
        </div>
      </div>
    </div>
{% endblock content %}
{% block scripts %}
<script>
  $(document).ready(()=>{

    // レコードの削除
    $('.delete-btn').on('click', function(){ // 削除ボタンクリック時

      $('#delete-confirmation-message').text(this.dataset.delete_confirmation_message);
      $('#deleteModal').modal('show');
      $('#deletion-submitted').off('click');
      $('#deletion-submitted').on('click', null, this.dataset.id, function(obj_event){
        $('#deleteModal').modal('hide');

        // 削除用 URL を POST で叩く
        $.ajax({
          url: '/authors/' + obj_event.data + '/delete/',
          method: 'POST',
          headers: {'X-CSRFToken': dict_utilities.getValueFromCookie('csrftoken')},
        }).done(() =>{
          location.reload();
        });

      });
    });

    // CSV 入力
    $('#csv-input-btn').on('click', function(){ // CSV 入力ボタンクリック時
      $('#CSVInputModal').modal('show');
    });
  });
</script>
{% endblock scripts %}