Django/example/13-manytomany-field/main/editors/urls.py
from django.urls import path

from . import views

app_name = 'editors'
urlpatterns = [
    path('create/', views.EditorCreate.as_view(), name = 'create'),
    path('', views.EditorsList.as_view(), name = 'list'), # Read
    path('<int:pk>/update/', views.EditorUpdate.as_view(), name = 'update'),
    path('<int:pk>/delete/', views.EditorDelete.as_view(), name = 'delete'),
    path('export_as_csv/', views.export_as_csv, name = 'export_as_csv'),
    path('import_from_csv/', views.import_from_csv, name = 'import_from_csv'),
]

Django/example/13-manytomany-field/main/index/urls.py
from django.urls import path

from . import views

app_name = 'index'
urlpatterns = [
    path('create/', views.BookCreate.as_view(), name = 'create'),
    path('', views.Index.as_view(), name = 'index'),
    path('<int:pk>/update/', views.BookUpdate.as_view(), name = 'update'),
    path('<int:pk>/delete/', views.BookDelete.as_view(), name = 'delete'),
    path('export_as_csv/', views.export_as_csv, name = 'export_as_csv'),
    path('import_from_csv/', views.import_from_csv, name = 'import_from_csv'),
]

Django/example/13-manytomany-field/main/main/urls.py
from django.contrib import admin
from django.urls import path, include # <- `include` を追加

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('admin/', admin.site.urls),

    # note
    # 第1引数には ``<`~python.exe manage.py startapp xxx` で作成したアプリ名>/`` を指定
    # 第2引数には ``include('<`~python.exe manage.py startapp xxx` で作成したアプリ名>.urls')`` を指定
    path('editors/', include('editors.urls')),
    path('accounts/', include('accounts.urls')),
    path('authors/', include('authors.urls')),
    path('', include('index.urls')),
    # URL で API のメジャーバージョンが指定できるように、`v1/` を URL に追加
    path('api/v1/', include('common.apiv1_urls')),
    
    # Open API 準拠の API ドキュメント生成の為の定義
    # https://drf-spectacular.readthedocs.io/en/latest/readme.html#take-it-for-a-spin
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

Django/example/13-manytomany-field/main/templates/index/form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load i18n static %}

{% block title %}書籍の{% if object %}編集{% else %}追加{% endif %}{% endblock title %}

{% block content %}
    <h4 class="mt-4 mb-5 border-bottom">書籍の{% if object %}編集{% else %}追加{% endif %}</h4>
    <form method="post">
      {% csrf_token %}{# Cross Site Request Forgery protection https://docs.djangoproject.com/en/4.0/ref/csrf/ #}
      
      {# note #}
      {# `field=form.name` の `=` にはスペースをいれてはならない #}
      {% include "form.html" with obj_field=form.name str_help_message="書籍の名前を入力します。"%}
      {% include "form.html" with obj_field=form.author str_help_message="任意で著者を選択します。"%}
      {% include "form_dual.html" with obj_field=form.editors str_help_message="任意で編集者を選択します。"%}
      
      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <button type="submit" class="btn btn-primary">登録</button>
        </div>
      </div>
    </form>
    <a href="{% url 'editors:list' %}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}

{% block scripts %}
<link href="{% static 'css/bootstrap-duallistbox.css' %}" rel="stylesheet" type="text/css"  />
<script src="{% static 'js/jquery.bootstrap-duallistbox.js' %}"></script>
{% endblock scripts %}

Django/example/13-manytomany-field/main/templates/index/index.html
{% extends "base.html" %}

{% block title %}書籍の一覧{% endblock title %}

{% block content %}
    <h4 class="mt-4 border-bottom">書籍の一覧</h4>
    <a href="{% url 'index:create' %}" class="btn btn-primary btn-sm my-3">追加</a>
    <a href="{% url 'index:export_as_csv' %}" class="btn btn-primary btn-sm my-3">CSV 出力</a>
    <button class="btn btn-primary btn-sm my-3" id="csv-input-btn">CSV 入力</button>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">著書名</th>
          <th scope="col">著者</th>
          <th scope="col">編集者</th>
          <th scope="col">操作</th>
        </tr>
      </thead>
      <tbody>
        {% for book in object_list %}
        <tr>
          <th scope="row">{{ book.id }}</th>
          <td>{{ book.name }}</td>
          <td>{% if book.author %}{{ book.author }}{% else %}不明な著者{% endif %}</td>
          <td>{% if book.editorsForView %}{{ book.editorsForView }}{% else %}不明な編集者{% endif %}</td>
          <td>
            <a href="{% url 'index:update' book.id %}" class="btn btn-outline-primary btn-sm">編集</a>
            <a href="javascript:void(0)" data-id="{{ book.id }}" data-delete_confirmation_message="著者 {{ book.name }} を削除しますか？" class="btn btn-outline-primary btn-sm delete-btn">削除</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    
    <!-- 削除を確認するモーダルダイアログ -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">削除確認</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p id="delete-confirmation-message"></p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
            <button type="button" class="btn btn-primary" id="deletion-submitted">削除</button>
          </div>
        </div>
      </div>
    </div>
    <!-- CSV 入力のモーダルダイアログ -->
    <div class="modal fade" id="CSVInputModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">CSV 入力</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <form action="{% url "index:import_from_csv" %}" enctype="multipart/form-data" method="post">
            <div class="modal-body">
              {% csrf_token %}
              <div class="mb-2">
                <input type="file" name="file" class="form-control" id="csv-input">
              </div>
              <div class="mb-2">
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="mode" id="inlineRadio1" value="update" checked>
                  <label class="form-check-label" for="inlineRadio1">更新及び追加</label>
                </div>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="mode" id="inlineRadio2" value="replace">
                  <label class="form-check-label" for="inlineRadio2">置き換え</label>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
              <input type="submit" class="btn btn-primary" value="反映"></input>
            </div>
          </form>
        </div>
      </div>
    </div>
{% endblock content %}
{% block scripts %}
<script>
  $(document).ready(()=>{

    // レコードの削除
    $('.delete-btn').on('click', function(){ // 削除ボタンクリック時

      $('#delete-confirmation-message').text(this.dataset.delete_confirmation_message);
      $('#deleteModal').modal('show');
      $('#deletion-submitted').off('click');
      $('#deletion-submitted').on('click', null, this.dataset.id, function(obj_event){
        $('#deleteModal').modal('hide');

        // 削除用 URL を POST で叩く
        $.ajax({
          url: '/' + obj_event.data + '/delete/',
          method: 'POST',
          headers: {'X-CSRFToken': dict_utilities.getValueFromCookie('csrftoken')},
        }).done(() =>{
          location.reload();
        });

      });
    });

    // CSV 入力
    $('#csv-input-btn').on('click', function(){ // CSV 入力ボタンクリック時
      $('#CSVInputModal').modal('show');
    });
  });
</script>
{% endblock scripts %}